#!/usr/bin/env node
/**
 * Sets up a macOS launchd job that runs the weekly digest pipeline
 * every Sunday at 11pm PT (Monday 7am UTC).
 *
 * The job:
 *   1. fetch_bookmarks.js  — scrapes Chrome bookmarks
 *   2. weekly_digest_generator.py — scores, writes articles, commits, sends test email
 *
 * Usage:
 *   node scripts/setup_launchd.js          # install
 *   node scripts/setup_launchd.js --remove # uninstall
 *   node scripts/setup_launchd.js --run    # run right now (test)
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const LABEL = 'tech.agenticedge.weekly-digest';
const PLIST_PATH = path.join(os.homedir(), 'Library/LaunchAgents', `${LABEL}.plist`);
const REPO_ROOT = path.resolve(__dirname, '..');
const LOG_DIR = path.join(REPO_ROOT, 'logs');
const LOG_FILE = path.join(LOG_DIR, 'weekly-digest.log');
const SCRIPT = path.join(REPO_ROOT, 'scripts/run_weekly_digest.sh');

// Sunday at 11pm PT = Monday 7am UTC = Weekday 1, Hour 7
// launchd uses local time, so we need PT = UTC-7 (PDT) or UTC-8 (PST)
// Sunday 23:00 PT
const PLIST = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>

  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${SCRIPT}</string>
  </array>

  <key>StartCalendarInterval</key>
  <dict>
    <key>Weekday</key>
    <integer>0</integer>
    <key>Hour</key>
    <integer>18</integer>
    <key>Minute</key>
    <integer>0</integer>
  </dict>

  <key>StandardOutPath</key>
  <string>${LOG_FILE}</string>
  <key>StandardErrorPath</key>
  <string>${LOG_FILE}</string>

  <key>RunAtLoad</key>
  <false/>

  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
    <key>HOME</key>
    <string>${os.homedir()}</string>
  </dict>
</dict>
</plist>`;

// The shell script that runs the full pipeline
function buildRunScript() {
  // Find node and python paths
  let nodePath = '/usr/local/bin/node';
  let pythonPath = '/usr/bin/python3';
  try { nodePath = execSync('which node', { encoding: 'utf8' }).trim(); } catch (_) {}
  try { pythonPath = execSync('which python3', { encoding: 'utf8' }).trim(); } catch (_) {}

  const envPath = path.join(REPO_ROOT, '.env');

  return `#!/bin/bash
# Agentic Edge — Weekly Digest Pipeline
# Auto-generated by setup_launchd.js — do not edit manually
# Runs every Sunday at 6pm PT
# NOTE: secrets loaded from .env at runtime — never hardcoded here

set -e
cd "${REPO_ROOT}"

echo ""
echo "========================================="
echo "Agentic Edge Weekly Digest — $(date)"
echo "========================================="

# Load secrets from .env (never committed to git)
if [ -f "${envPath}" ]; then
  set -a
  source "${envPath}"
  set +a
else
  echo "ERROR: .env not found at ${envPath}"
  exit 1
fi

export REPO_PATH="${REPO_ROOT}"

# Step 1: Scrape bookmarks from Chrome
echo ""
echo "[1/2] Fetching bookmarks from Chrome..."
BOOKMARKS_FILE="${REPO_ROOT}/bookmarks_$(date +%Y-%m-%d).json"
"${nodePath}" "${REPO_ROOT}/scripts/fetch_bookmarks.js" --max 200 --output "$BOOKMARKS_FILE"
echo "Bookmarks saved to $BOOKMARKS_FILE"

# Step 2: Run the digest generator
echo ""
echo "[2/2] Running digest generator..."
export BOOKMARKS_JSON_PATH="$BOOKMARKS_FILE"
"${pythonPath}" "${REPO_ROOT}/scripts/weekly_digest_generator.py"

echo ""
echo "Done! Check pillicdj@gmail.com for the test email."
echo "Cron fires Monday 1pm PT to send to all subscribers."
`;
}

function install() {
  // Create logs dir
  if (!fs.existsSync(LOG_DIR)) fs.mkdirSync(LOG_DIR, { recursive: true });

  // Write the shell runner
  const runScript = buildRunScript();
  fs.writeFileSync(SCRIPT, runScript, { mode: 0o755 });
  console.log(`✓ Created runner: ${SCRIPT}`);

  // Write plist
  fs.mkdirSync(path.dirname(PLIST_PATH), { recursive: true });
  fs.writeFileSync(PLIST_PATH, PLIST);
  console.log(`✓ Created plist: ${PLIST_PATH}`);

  // Unload existing (if any), then load
  try { execSync(`launchctl unload "${PLIST_PATH}" 2>/dev/null`); } catch (_) {}
  execSync(`launchctl load "${PLIST_PATH}"`);
  console.log(`✓ Loaded into launchd`);

  console.log('');
  console.log('Schedule: Every Sunday at 6:00 PM PT');
  console.log(`Logs:     ${LOG_FILE}`);
  console.log('');
  console.log('To run now:   node scripts/setup_launchd.js --run');
  console.log('To uninstall: node scripts/setup_launchd.js --remove');
  console.log('To check:     launchctl list | grep agenticedge');
}

function remove() {
  try {
    execSync(`launchctl unload "${PLIST_PATH}"`);
    console.log('✓ Unloaded from launchd');
  } catch (_) {}
  if (fs.existsSync(PLIST_PATH)) {
    fs.unlinkSync(PLIST_PATH);
    console.log(`✓ Removed ${PLIST_PATH}`);
  }
  if (fs.existsSync(SCRIPT)) {
    fs.unlinkSync(SCRIPT);
    console.log(`✓ Removed ${SCRIPT}`);
  }
  console.log('Done.');
}

function runNow() {
  console.log('Running digest pipeline now...');
  console.log(`Logs: ${LOG_FILE}`);
  console.log('');

  // Regenerate the script with fresh env vars (in case .env changed)
  if (!fs.existsSync(LOG_DIR)) fs.mkdirSync(LOG_DIR, { recursive: true });
  const runScript = buildRunScript();
  fs.writeFileSync(SCRIPT, runScript, { mode: 0o755 });

  try {
    execSync(`/bin/bash "${SCRIPT}"`, { stdio: 'inherit' });
  } catch (e) {
    console.error('Pipeline failed. Check logs above.');
    process.exit(1);
  }
}

const arg = process.argv[2];
if (arg === '--remove') {
  remove();
} else if (arg === '--run') {
  runNow();
} else {
  install();
}
